import { Besley } from "next/font/google";
import "./globals.css";
import "@material/web/button/filled-button.js";
import "@material/web/button/outlined-button.js";
import "@material/web/checkbox/checkbox.js";
import "primereact/resources/themes/lara-light-cyan/theme.css";
// import "primereact/resources/themes/lara-light-cyan/theme.css";
import { PrimeReactProvider } from "primereact/api";
import { Toaster } from "react-hot-toast";
import { ClothesWrapper } from "@/context/clothes_context";
import { UserWrapper } from "@/context/user_context";
import { Suspense } from "react";
import { GlobalProvider } from "@/context/global_context";
import GlobalLoader from "@/components/general/loader";
import PageLoader from "@/components/general/loader_page";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Container from "@/components/general/container";
import Header from "@/components/layouts/navbar";
import CustomFooter from "@/components/layouts/footer";
import { AdminProvider } from "@/context/admin_context";

const besley = Besley({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Ethrift Mongolia",
  description: "Generated by Temuulen",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" ">
        <PrimeReactProvider value={{ unstyled: true }}>
          <GlobalProvider>
            <UserWrapper>
              <AdminProvider>
                <ClothesWrapper>
                  <AntdRegistry>
                    <Toaster
                      toastOptions={{
                        style: { background: "rgb(51 65 85)", color: "#fff" },
                        position: "bottom-left",
                      }}
                    />
                    {/* <Toaster position="bottom-right" /> */}
                    <Suspense fallback={<PageLoader />}>
                      <GlobalLoader />
                      <main>
                        <div className="flex flex-col min-h-screen justify-between">
                          <div>
                            <Header />
                            <main
                            // className="flex-grow"
                            >
                              {children}
                            </main>
                          </div>
                          <CustomFooter />
                        </div>
                      </main>
                    </Suspense>
                  </AntdRegistry>
                </ClothesWrapper>
              </AdminProvider>
            </UserWrapper>
          </GlobalProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
