import { Poppins } from "next/font/google";
import "./globals.css";
import "@material/web/button/filled-button.js";
import "@material/web/button/outlined-button.js";
import "@material/web/checkbox/checkbox.js";
import { Toaster } from "react-hot-toast";
import { ClothesWrapper } from "@/context/clothes_context";
import { UserWrapper } from "@/context/user_context";
import { Suspense } from "react";
import { GlobalProvider } from "@/context/global_context";
import GlobalLoader from "@/components/general/loader";
import PageLoader from "@/components/general/loader_page";
import Container from "@/components/general/container";
import Header from "@/components/layouts/Header";
import CustomFooter from "@/components/layouts/footer";
import { AdminProvider } from "@/context/admin_context";
import AdminSideBar from "@/components/admin_layout/admin_sidebar";
const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Ethrift admin",
  description: "Generated by Temuulen",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" ">
        <GlobalProvider>
          <UserWrapper>
            <AdminProvider>
              <ClothesWrapper>
                <Toaster
                  toastOptions={{
                    style: { background: "rgb(51 65 85)", color: "#fff" },
                    position: "bottom-left",
                  }}
                />
                {/* <Toaster position="bottom-right" /> */}
                <Suspense fallback={<PageLoader />}>
                  <GlobalLoader />
                  <main>
                    <div className="grid  grid-cols-12 min-h-screen justify-between">
                      {/* <Header /> */}
                      <div className="col-span-2">
                        <AdminSideBar />
                      </div>
                      <main className="col-span-10 ">
                        <Container>{children}</Container>
                      </main>
                      {/* <CustomFooter /> */}
                    </div>
                  </main>
                </Suspense>
              </ClothesWrapper>
            </AdminProvider>
          </UserWrapper>
        </GlobalProvider>
      </body>
    </html>
  );
}
